# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
better_home: &better_home
  facebook_app_id: <%= ENV["facebook_app_id"] %>
  facebook_app_secret: <%= ENV["facebook_app_secret"] %>
  zillow_zwsid: <%= ENV["ZILLOW_ZWSID"] %>
  trulia_api_key: <%= ENV['TRULIA_API_KEY'] %>
  walkscore_key: <%= ENV["WALKSCORE_KEY"] %>
  factual_key: <%= ENV["FACTUAL_KEY"] %>
  factual_secret: <%= ENV["FACTUAL_SECRET"] %>
  yelp_con_key: <%= ENV["YELP_CON_KEY"] %>
  yelp_con_secret: <%= ENV["YELP_CON_SECRET"] %>
  yelp_token: <%= ENV["YELP_TOKEN"] %>
  yelp_token_secret: <%= ENV["YELP_TOKEN_SECRET"] %>
  google_maps_key: <%= ENV["GOOGLE_MAPS_KEY"] %>


development:
  secret_key_base: a01b81b4200b161c048d6d266ebd19c3ade584063ac5d5f7c31c1434182b7992b223fa85350693bb51d93a1327ea99019d2534d0dfb6a8a73b7e783c07ff3cdb
  <<: *better_home

test:
  secret_key_base: 259f1e6f98185daab0e8fac773789be1bdef85f642d5b96c1b4668b750b9aee4bb79521c6c76ef06d2da4d4c534e4062b3ac266c3584e998680e2dee6ad42b0f
  <<: *better_home

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  <<: *better_home
